import LinkedListNode from "./Data Structures/LinkedListNode";
import LinkedList from "./Data Structures/LinkedList";

let list = new LinkedList()
list.append(2000)
list.append(4)
list.append(6)
list.append(8)
list.append(2)
list.append(1000000)
// list.print()
// console.log('------------------')
// list.append(10)
// list.append(12)
// list.append(14)
// list.print()
// console.log('------------------')
// list.deleteAll(2)
// list.print()
// console.log('------------------')
// list.deleteAll(14)
// list.print()

list.deleteHead()
list.deleteTail()